
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app.kubernetes.io/name: nginx
#   name: my-service
#   namespace: default
# spec:
#   externalTrafficPolicy: Cluster
#   ports:
#   - nodePort: 30431
#     port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     app.kubernetes.io/name: nginx
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer:
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-nginx
#   labels:
#     run: my-nginx
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     protocol: TCP
#   selector:
#     run: my-nginx
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    run: my-nginx
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80